config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#top'
  resources :books
  resources :users
  get 'home/about' => 'home#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :books, dependent: :destroy

  validates :name, presence: true

  validates :name, length: { in: 2..20 }

  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!, except: [:top, :about]
before_action :configure_permitted_parameters, if: :devise_controller?

protected
def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :email])
end

def after_sign_in_path_for(resource)
    user_path(current_user.id)
end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def show
  	  @book = Book.find(params[:id])
      @user = current_user
      @newbook = Book.new
  end

  def index
      @books = Book.all
      @user = current_user
      @book = Book.new
  end

  def edit
      @book =Book.find(params[:id])
   if @book.user_id != current_user.id
      redirect_to books_path
  end
end

  def update
      @book = Book.find(params[:id])
   if @book.update(book_params)
      flash[:notice] = "successfully"
      redirect_to book_path(@book)
  else
      render 'edit'
  end
end

  def create
      @book = Book.new(book_params)
      @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "successfully"
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render 'index'
    end
  end

  def destroy
      book = Book.find(params[:id])
      book.destroy
      redirect_to books_path
  end



private
  def book_params
      params.require(:book).permit(:title, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  	  flash[:notice] = "successfully"
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def index
  	  @users = User.all
      @user = current_user
      @book = Book.new
  end

  def show
      @book = Book.new
  	  @user = User.find(params[:id])
      @books = @user.books
  end

  def edit
  	  @user = User.find(params[:id])
   if @user.id != current_user.id
      redirect_to user_path(current_user.id)
  end
  end

  def update
      @user = User.find(params[:id])
   if @user.update(user_params)
      flash[:notice] = "successfully"
      redirect_to user_path(@user)
      else
      render'edit'
      end
  end

  def create
  end

private
  def user_params
      params.require(:user).permit(:profile_image, :name, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation">
  	<h2><%= @book.errors.count %>error! </h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container-fluid">
  <div class="center-block">
    <div class="row">
      <div class="col-xs-3"></div>
	  <div class="col-xs-6">
		<h2> Editing Book</h2>
		<%= form_for(@book) do |f| %>
		<strong>Title</strong>
			<p><%= f.text_field :title, class:"form-control" %></p>
		<strong>Opinion</strong>
		<p><%= f.text_area :body, class:"form-control" %></p>
		<%= f.submit "Update Book", :class=>"btn btn-primary btn-lg btn-block" %>
		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}"%> |
		<%= link_to 'Back', books_path, class: "back"%>
		<% end %>
	  </div>
	  <div class="col-xs-3"></div>
	</div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
    <h3><%= @book.errors.count %>error occurrence</h3>
    <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
  </div>
<% end %>
<div class="container">
  <div class="row">
  <%= render'users/sidebar', user:@user, book:@book %>
    <div class="col-xs-9">
      <h2>Books</h2>
        <table class="table table-hover">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
            </tr>
          </thead>
          <tbody>
              <% @books.each do |book| %>
                <td>
                  <%= link_to user_path(book.user.id) do %>
                  <%= attachment_image_tag book.user, :profile_image, class: "pull-left profile-thumb", fallback: "no_image.jpg", size:'45x45'%>
                  <% end %>
                </th>
                <th><%= link_to book.title, book_path(book.id), class: "book_#{book.id}"%></th>
                <th><%= book.body %></th>
            </tr>
              <% end %>
          </tbody>
        </table>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>
<div class="container">
  <div class="row">
   <%= render'users/sidebar', user:@book.user, book:@newbook %>
   <div class="col-xs-9">
        <h2>Book detail</h2>
          <table class="table">
            <thead>
              <tr></tr>
            </thead>
              <tbody>
                <tr>
                  <td>
                    <%= link_to user_path(@book.user.id) do %>

                    <%= attachment_image_tag @book.user, :profile_image, class: "pull-left profile-thumb", fallback: "no_image.jpg", size:'45x45'%>
                    <%= @book.user.name %>
                    <% end %>
                  </td>
                  <td><%= @book.title %></th>
                  <td><%= @book.body %></th>
                  <% if current_user.id == @book.user_id %>
                  <td><%= link_to "Edit",edit_book_path(@book.id), class: "btn-sm btn-success edit_book_#{@book.id}"%></td>
                  <td><%= link_to "Destroy", book_path(@book.id), method: :delete,  data: {confirm: "本当に削除しますか？"},class: "btn-sm btn-danger destroy_book_#{@book.id}"%></td>
                  <% end %>
                </tr>
              </tbody>
            </thead>
          </table>
    </div>
  </div>
</div>

app/views/home.html.erb/about.html.erb
about.html.erb

app/views/home/about.html.erb
<header>

  <div class="container">
    <p id="notice"></p>
    <h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>
  </div>

</header>

app/views/home/top.html.erb
<% if flash[:notice] %>
  <div class="flash">
<%= flash[:notice] %>
  </div>
<% end %>
<div class ="container">

  <div class="row">
    <div class="top-message col-md-offset-3 col-md-6">
    <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong> !!</span></h1>
    <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
    <p>you can share and exchange  your opinions , inpressions , and emotions</p>
    <p> about varioius books!</p>

    <%= link_to 'log in',new_user_session_path, class: 'btn btn-info btn-lg btn-block' %>
    <%= link_to 'sign up', new_user_registration_path, class: 'btn btn-success btn-lg btn-block'%>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class='nav navbar-nav navbar-left' >
          <a class="navbar-brand" href="">
            <span>Bookers</span>
          </a>
        </nav>

  <nav>
    <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Home", user_path(current_user), class: "glyphicon glyphicon-home home" %>
        </li>
        <li>
          <a class="glyphicon glyphicon-user user" href="/users"> Users</a>
        </li>
        <li>
          <a class="glyphicon glyphicon-book books" href="/books"> Books</a>
        </li>
        <li>
          <%= link_to "logout", destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %>

          </li>
      </ul>

      <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a class="glyphicon glyphicon-home home" href="/"> Home</a>
        </li>
        <li>
          <a class="glyphicon glyphicon-link about" href="/home/about"> About</a>
        </li>
        <li>
          <a class="glyphicon glyphicon-edit sign_up" href="/users/sign_up"> sign up</a>
        </li>
        <li>
          <a class="glyphicon glyphicon-log-in sign_in" href="/users/sign_in"> login</a>
        </li>
      </ul>
    <% end %>
  </nav>
      </div>
    </header>

  <div class='body'>
    <div class='margin'></div>
  </div>

  <main>
  <%= yield %>
  </main>

  <div class="container">
    <footer>
      <p><div align="right">CopyRight Infratop.inc</div></p>
    </footer>
  </div>

</body>
</html>

app/views/users/_sidebar.html.erb
<div class="col-xs-3">
      <h2>User info</h2>
      <div class="noimage">
        <div class="user-edit-image">
              <%= attachment_image_tag user, :profile_image, :fill, 100, 100, class: "pull-left profile-thumb", fallback: "no_image.jpg"%>
        </div>
      </div>

    <table class=table>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th width="140">introduction</th>
        <th><%= user.introduction %></th>

      </tr>
    </table>

    <%= link_to "",edit_user_path(user.id) ,class: "btn btn-default btn-lg btn-block glyphicon glyphicon-wrench" %>

<%= form_for(book) do |f| %>
    <div class="field row">
        <%= f.label :title %>
        <%= f.text_field :title, class: "col-xs-12 book_title" %>
    </div>

    <div class="field row">
        <%= f.label :body %>
        <%= f.text_area :body, class: "col-xs-12 book_body" %>
    </div>

    <div class="actions row">
        <%= f.submit class: "btn btn-primary col-xs-12" %>
    </div>
<% end %>
</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
  	<h2><%= @user.errors.count %>error! </h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class=container>

<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->

<div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "name" %>
</div>

<div class="field">
    <%= f.label :image %>
    <%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
    <%= f.label :introduction %>
    <%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
    <%= f.submit %>
</div>

<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
<%= render'users/sidebar', user:@user, book:@book %>
    <div class="col-xs-9">
      <h2> Users</h2>
        <table class="table table-hover">
  	      <thead>
  		      <tr>
  			      <th>image</th>
  			      <th>name</th>
              <th></th>
     	      </tr>
  	      </thead>
          <tbody>
            <% @users.each do |user| %>
                <th><%= attachment_image_tag @user, :profile_image, class: "pull-left profile-thumb", fallback: "no_image.jpg", size:'45x45'%></th>
                <th><%= user.name %></th>
                <th><%=link_to "Show",user_path(user.id)%></th>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>
<div class="container">
  <div class="row">
    <%= render'users/sidebar', user:@user, book:@book %>

    <div class="col-xs-9">
      <h2>Books</h2>
        <table class="table table-hover">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
            </tr>
          </thead>
          <% @books.each do |book| %>
        <tbody>
          <tr>
              <td><%= attachment_image_tag @user, :profile_image, class: "pull-left profile-thumb", fallback: "no_image.jpg", size:'45x45'%></td>
              <td><%= link_to book.title, book_path(book.id)%></td>
              <td><%= book.body %></td>
          </tr>
         </tbody>
         <% end %>
        </table>
    </div>
  </div>
</div>